theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "backlight"

[[block]]
block = "net"
device = "wlp58s0"
ssid = true
interval = 30
speed_up = false
speed_down = false

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
